/**
 * ResNet-18 end-to-end inference test (CPU + CUDA).
 *
 * Requires the model and test data generated by gen_resnet_test.py.
 * Input:  1×3×224×224 F32 random tensor
 * Output: 1×1000 F32 logits
 * Reference: PyTorch output (also verified against ONNX Runtime)
 */

#include "unity.h"
#include "inference_engine.h"
#include "platform.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifdef USE_CUDA
#include "cuda_platform.h"
#endif

extern int operator_init_all(void);

void setUp(void) {}
void tearDown(void) {}

static int load_binary(const char* path, void* buf, size_t expected_bytes) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "Cannot open %s\n", path); return -1; }
    size_t n = fread(buf, 1, expected_bytes, f);
    fclose(f);
    if (n != expected_bytes) {
        fprintf(stderr, "Short read from %s: %zu/%zu\n", path, n, expected_bytes);
        return -1;
    }
    return 0;
}

/* --------------------------------------------------------------------------
 * Softmax + top-5 for human-readable output
 * -------------------------------------------------------------------------- */
static void softmax(const float* logits, float* probs, int n) {
    float max_val = logits[0];
    for (int i = 1; i < n; i++) if (logits[i] > max_val) max_val = logits[i];
    float sum = 0.0f;
    for (int i = 0; i < n; i++) { probs[i] = expf(logits[i] - max_val); sum += probs[i]; }
    for (int i = 0; i < n; i++) probs[i] /= sum;
}

static void print_top5(const float* probs, int n) {
    int idx[5] = {0}; float val[5] = {0};
    for (int i = 0; i < n; i++) {
        for (int k = 0; k < 5; k++) {
            if (probs[i] > val[k]) {
                /* shift down */
                for (int j = 4; j > k; j--) { val[j] = val[j-1]; idx[j] = idx[j-1]; }
                val[k] = probs[i]; idx[k] = i;
                break;
            }
        }
    }
    printf("Top-5 predictions:\n");
    for (int i = 0; i < 5; i++) printf("  Class %4d: prob=%.6f\n", idx[i], val[i]);
}

/* --------------------------------------------------------------------------
 * CPU inference test
 * -------------------------------------------------------------------------- */
void test_resnet18_cpu(void) {
    fprintf(stderr, "\n=== ResNet-18 CPU Inference ===\n");

    /* 1. Load model */
    inference_session_t* sess = inference_session_load("tests/resnet18_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: model load returned NULL\n"); return; }
    fprintf(stderr, "Model loaded: %zu inputs, %zu outputs\n",
           (size_t)inference_session_num_inputs(sess),
           (size_t)inference_session_num_outputs(sess));

    /* 2. Load input image (random tensor, 1x3x224x224) */
    int64_t input_shape[] = {1, 3, 224, 224};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, input_shape);
    if (!input) { fprintf(stderr, "FAIL: tensor_create input\n"); goto cleanup_sess; }
    if (load_binary("tests/resnet18_input.bin", input->data,
                    1 * 3 * 224 * 224 * sizeof(float)) != 0) {
        fprintf(stderr, "FAIL: load input binary\n"); goto cleanup_input;
    }

    /* 3. Create output tensor (1x1000) */
    int64_t output_shape[] = {1, 1000};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, output_shape);
    if (!output) { fprintf(stderr, "FAIL: tensor_create output\n"); goto cleanup_input; }

    /* 4. Run inference */
    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        int rc = inference_session_run(sess, inputs, outputs, 0);
        if (rc != 0) {
            fprintf(stderr, "FAIL: inference_session_run\n"); goto cleanup_output;
        }
    }

    /* 5. Load reference and compare */
    {
        float ref[1000];
        if (load_binary("tests/resnet18_ref_output.bin", ref, sizeof(ref)) != 0) {
            fprintf(stderr, "FAIL: load ref output\n"); goto cleanup_output;
        }

        float probs[1000], ref_probs[1000];
        softmax((float*)output->data, probs, 1000);
        softmax(ref, ref_probs, 1000);

        fprintf(stderr, "\nReference (PyTorch):\n"); print_top5(ref_probs, 1000);
        fprintf(stderr, "\nCudaForge (CPU):\n");   print_top5(probs, 1000);

        /* Check each output within 1e-2 of reference */
        int mismatch = 0;
        float max_diff = 0.0f;
        for (int i = 0; i < 1000; i++) {
            float diff = fabsf(((float*)output->data)[i] - ref[i]);
            if (diff > max_diff) max_diff = diff;
            if (diff > 1e-2f) mismatch++;
        }
        fprintf(stderr, "\nMax abs diff vs PyTorch: %.2e (%d/1000 beyond 1e-2)\n",
               max_diff, mismatch);

        /* Top-1 prediction should match */
        float max_prob = 0; int top1_cpu = -1;
        float max_ref  = 0; int top1_ref = -1;
        for (int i = 0; i < 1000; i++) {
            if (probs[i] > max_prob) { max_prob = probs[i]; top1_cpu = i; }
            if (ref_probs[i] > max_ref) { max_ref = ref_probs[i]; top1_ref = i; }
        }
        fprintf(stderr, "Top-1: CPU=%d (prob=%.4f)  PyTorch=%d (prob=%.4f)\n",
               top1_cpu, max_prob, top1_ref, max_ref);
        fprintf(stderr, "Max diff: %.2e  Mismatches>1e-2: %d/1000\n",
               max_diff, mismatch);
    }

cleanup_output:
    tensor_destroy(output);
cleanup_input:
    tensor_destroy(input);
cleanup_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * CUDA inference test
 * -------------------------------------------------------------------------- */
void test_resnet18_cuda(void) {
    fprintf(stderr, "\n=== ResNet-18 CUDA Inference ===\n");

    /* 1. Load model */
    inference_session_t* sess = inference_session_load("tests/resnet18_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: CUDA model load NULL\n"); return; }
    fprintf(stderr, "CUDA Model loaded: %zu inputs, %zu outputs\n",
           (size_t)inference_session_num_inputs(sess),
           (size_t)inference_session_num_outputs(sess));

    /* 2. Load input */
    int64_t input_shape[] = {1, 3, 224, 224};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, input_shape);
    if (!input) { fprintf(stderr, "FAIL: CUDA tensor_create input\n"); goto cu_cleanup_sess; }
    if (load_binary("tests/resnet18_input.bin", input->data,
                    1 * 3 * 224 * 224 * sizeof(float)) != 0) {
        fprintf(stderr, "FAIL: CUDA load input\n"); goto cu_cleanup_input;
    }

    /* 3. Create output */
    int64_t output_shape[] = {1, 1000};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, output_shape);
    if (!output) { fprintf(stderr, "FAIL: CUDA tensor_create output\n"); goto cu_cleanup_input; }

    /* 4. Run CUDA inference */
    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        fprintf(stderr, "CUDA: running inference...\n");
        int rc = inference_session_run(sess, inputs, outputs, 1);
        fprintf(stderr, "CUDA: inference result=%d\n", rc);
        if (rc != 0) {
            fprintf(stderr, "FAIL: CUDA inference_session_run\n"); goto cu_cleanup_output;
        }
    }

    /* 5. Compare with reference */
    {
        float ref[1000];
        if (load_binary("tests/resnet18_ref_output.bin", ref, sizeof(ref)) != 0) {
            fprintf(stderr, "FAIL: CUDA load ref\n"); goto cu_cleanup_output;
        }

        float probs[1000], ref_probs[1000];
        softmax((float*)output->data, probs, 1000);
        softmax(ref, ref_probs, 1000);

        fprintf(stderr, "\nCudaForge (CUDA):\n"); print_top5(probs, 1000);

        float max_diff = 0.0f;
        int mismatch = 0;
        for (int i = 0; i < 1000; i++) {
            float diff = fabsf(((float*)output->data)[i] - ref[i]);
            if (diff > max_diff) max_diff = diff;
            if (diff > 1e-2f) mismatch++;
        }
        fprintf(stderr, "Max abs diff vs PyTorch: %.2e (%d/1000 beyond 1e-2)\n",
               max_diff, mismatch);

        float max_prob = 0; int top1_cuda = -1;
        float max_ref  = 0; int top1_ref = -1;
        for (int i = 0; i < 1000; i++) {
            if (probs[i] > max_prob) { max_prob = probs[i]; top1_cuda = i; }
            if (ref_probs[i] > max_ref) { max_ref = ref_probs[i]; top1_ref = i; }
        }
        fprintf(stderr, "Top-1: CUDA=%d (prob=%.4f)  PyTorch=%d (prob=%.4f)\n",
               top1_cuda, max_prob, top1_ref, max_ref);
    }

cu_cleanup_output:
    tensor_destroy(output);
cu_cleanup_input:
    tensor_destroy(input);
cu_cleanup_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * Main
 * -------------------------------------------------------------------------- */
int main(void) {
    platform_init();
    operator_init_all();
#ifdef USE_CUDA
    cuda_platform_init(0);
#endif

    test_resnet18_cpu();
    fprintf(stderr, "\n=== ResNet-18 CPU: DONE ===\n");

#ifdef USE_CUDA
    test_resnet18_cuda();
    fprintf(stderr, "\n=== ResNet-18 CUDA: DONE ===\n");
    cuda_platform_finalize();
#endif
    platform_finalize();
    return 0;
}
