/**
 * BERT-like model end-to-end inference test (CPU + CUDA).
 *
 * Requires the model and test data generated by gen_bert_test.py.
 * Exercises LayerNorm, Gather (Embedding), Squeeze/Unsqueeze, and existing ops.
 * Input:  1×8 INT64 token IDs (stored as F32)
 * Output: 1×8×256 F32 logits
 * Reference: PyTorch ONNX Runtime output
 */

#include "unity.h"
#include "inference_engine.h"
#include "platform.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifdef USE_CUDA
#include "cuda_platform.h"
#endif

extern int operator_init_all(void);

void setUp(void) {}
void tearDown(void) {}

static int load_binary(const char* path, void* buf, size_t expected_bytes) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "Cannot open %s\n", path); return -1; }
    size_t n = fread(buf, 1, expected_bytes, f);
    fclose(f);
    if (n != expected_bytes) {
        fprintf(stderr, "Short read from %s: %zu/%zu\n", path, n, expected_bytes);
        return -1;
    }
    return 0;
}

static float max_abs_diff(const float* a, const float* b, int64_t n) {
    float maxd = 0.0f;
    for (int64_t i = 0; i < n; i++) {
        float d = fabsf(a[i] - b[i]);
        if (d > maxd) maxd = d;
    }
    return maxd;
}

/* --------------------------------------------------------------------------
 * CPU inference test
 * -------------------------------------------------------------------------- */
static void test_bert_cpu(void) {
    fprintf(stderr, "\n=== BERT-like CPU Inference ===\n");

    /* 1. Load model */
    inference_session_t* sess = inference_session_load("tests/bert_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: model load returned NULL\n"); return; }
    fprintf(stderr, "Model loaded: %zu inputs, %zu outputs\n",
           (size_t)inference_session_num_inputs(sess),
           (size_t)inference_session_num_outputs(sess));

    /* 2. Load input token IDs (1x8, stored as F32, convert to I64) */
    int64_t input_shape[] = {1, 8};
    tensor_t* input = tensor_create(DATA_TYPE_I64, 2, input_shape);
    if (!input) { fprintf(stderr, "FAIL: tensor_create input\n"); goto cleanup_sess; }
    {
        float tmp[8];
        if (load_binary("tests/bert_input.bin", tmp, 8 * sizeof(float)) != 0) {
            fprintf(stderr, "FAIL: load input binary\n"); goto cleanup_input;
        }
        int64_t* ids = (int64_t*)input->data;
        for (int i = 0; i < 8; i++) ids[i] = (int64_t)tmp[i];
    }

    /* 3. Create output tensor (1x8x256) */
    int64_t output_shape[] = {1, 8, 256};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 3, output_shape);
    if (!output) { fprintf(stderr, "FAIL: tensor_create output\n"); goto cleanup_input; }

    /* 4. Run inference */
    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        int rc = inference_session_run(sess, inputs, outputs, 0);
        if (rc != 0) {
            fprintf(stderr, "FAIL: inference_session_run = %d\n", rc);
            goto cleanup_output;
        }
    }

    /* 5. Load reference and compare */
    {
        float* ref = (float*)malloc(1 * 8 * 256 * sizeof(float));
        if (!ref) goto cleanup_output;
        if (load_binary("tests/bert_ref_output.bin", ref,
                        1 * 8 * 256 * sizeof(float)) != 0) {
            free(ref); goto cleanup_output;
        }

        float max_diff = max_abs_diff((float*)output->data, ref, 1 * 8 * 256);
        int mismatch = 0;
        for (int i = 0; i < 1 * 8 * 256; i++) {
            if (fabsf(((float*)output->data)[i] - ref[i]) > 1e-3f) mismatch++;
        }

        fprintf(stderr, "CPU  max_diff=%.2e  mismatches>1e-3: %d/%d\n",
               max_diff, mismatch, 1 * 8 * 256);

        /* Verify a few output values are non-zero (not all zeros) */
        int non_zero = 0;
        for (int i = 0; i < 1 * 8 * 256; i++)
            if (fabsf(((float*)output->data)[i]) > 1e-6f) non_zero++;
        fprintf(stderr, "CPU  non_zero outputs: %d/%d\n", non_zero, 1 * 8 * 256);

        if (max_diff < 1e-3f) {
            fprintf(stderr, "BERT CPU: PASS (max_diff=%.2e)\n", max_diff);
        } else {
            fprintf(stderr, "BERT CPU: max_diff=%.2e > 1e-3 (CHECK)\n", max_diff);
        }

        free(ref);
    }

cleanup_output:
    tensor_destroy(output);
cleanup_input:
    tensor_destroy(input);
cleanup_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * CUDA inference test
 * -------------------------------------------------------------------------- */
static void test_bert_cuda(void) {
    fprintf(stderr, "\n=== BERT-like CUDA Inference ===\n");

    /* 1. Load model */
    inference_session_t* sess = inference_session_load("tests/bert_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: CUDA model load NULL\n"); return; }

    /* 2. Load input (convert F32 → I64) */
    int64_t input_shape[] = {1, 8};
    tensor_t* input = tensor_create(DATA_TYPE_I64, 2, input_shape);
    if (!input) { fprintf(stderr, "FAIL: CUDA tensor_create input\n"); goto cu_cleanup_sess; }
    {
        float tmp[8];
        if (load_binary("tests/bert_input.bin", tmp, 8 * sizeof(float)) != 0) {
            fprintf(stderr, "FAIL: CUDA load input\n"); goto cu_cleanup_input;
        }
        int64_t* ids = (int64_t*)input->data;
        for (int i = 0; i < 8; i++) ids[i] = (int64_t)tmp[i];
    }

    /* 3. Create output */
    int64_t output_shape[] = {1, 8, 256};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 3, output_shape);
    if (!output) { fprintf(stderr, "FAIL: CUDA tensor_create output\n"); goto cu_cleanup_input; }

    /* 4. Run CUDA inference */
    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        fprintf(stderr, "CUDA: running inference...\n");
        int rc = inference_session_run(sess, inputs, outputs, 1);
        fprintf(stderr, "CUDA: inference result=%d\n", rc);
        if (rc != 0) {
            fprintf(stderr, "FAIL: CUDA inference_session_run\n"); goto cu_cleanup_output;
        }
    }

    /* 5. Compare with reference */
    {
        float* ref = (float*)malloc(1 * 8 * 256 * sizeof(float));
        if (!ref) goto cu_cleanup_output;
        if (load_binary("tests/bert_ref_output.bin", ref,
                        1 * 8 * 256 * sizeof(float)) != 0) {
            free(ref); goto cu_cleanup_output;
        }

        float max_diff = max_abs_diff((float*)output->data, ref, 1 * 8 * 256);
        fprintf(stderr, "CUDA max_diff=%.2e\n", max_diff);

        /* Count mismatches at a more relaxed threshold for GPU */
        int mismatch = 0;
        for (int i = 0; i < 1 * 8 * 256; i++) {
            if (fabsf(((float*)output->data)[i] - ref[i]) > 5e-3f) mismatch++;
        }
        fprintf(stderr, "CUDA mismatches>5e-3: %d/%d\n", mismatch, 1 * 8 * 256);

        free(ref);
    }

cu_cleanup_output:
    tensor_destroy(output);
cu_cleanup_input:
    tensor_destroy(input);
cu_cleanup_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * Phase B: BERT-base CPU inference test
 * Exercises Exp, ReduceSum, ReduceMax, Cast, ArgMax + all Phase A ops.
 * Input:  1×8 INT64 token IDs (stored as F32)
 * Output: 1×257 F32 (256 vocab softmax + 1 argmax index)
 * Reference: ONNX Runtime output
 * -------------------------------------------------------------------------- */
static void test_bert_base_cpu(void) {
    fprintf(stderr, "\n=== BERT-base CPU Inference (Phase B) ===\n");

    inference_session_t* sess = inference_session_load("tests/bert_base_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: model load returned NULL\n"); return; }
    fprintf(stderr, "Model loaded: %zu inputs, %zu outputs\n",
           (size_t)inference_session_num_inputs(sess),
           (size_t)inference_session_num_outputs(sess));

    int64_t input_shape[] = {1, 8};
    tensor_t* input = tensor_create(DATA_TYPE_I64, 2, input_shape);
    if (!input) { fprintf(stderr, "FAIL: tensor_create input\n"); goto base_cpu_cleanup_sess; }
    {
        float tmp[8];
        if (load_binary("tests/bert_base_input.bin", tmp, 8 * sizeof(float)) != 0) {
            fprintf(stderr, "FAIL: load input binary\n"); goto base_cpu_cleanup_input;
        }
        int64_t* ids = (int64_t*)input->data;
        for (int i = 0; i < 8; i++) ids[i] = (int64_t)tmp[i];
    }

    int64_t output_shape[] = {1, 257};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, output_shape);
    if (!output) { fprintf(stderr, "FAIL: tensor_create output\n"); goto base_cpu_cleanup_input; }

    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        int rc = inference_session_run(sess, inputs, outputs, 0);
        if (rc != 0) {
            fprintf(stderr, "FAIL: inference_session_run = %d\n", rc);
            goto base_cpu_cleanup_output;
        }
    }

    {
        int64_t n_elem = 1 * 257;
        float* ref = (float*)malloc(n_elem * sizeof(float));
        if (!ref) goto base_cpu_cleanup_output;
        if (load_binary("tests/bert_base_ref_output.bin", ref,
                        n_elem * sizeof(float)) != 0) {
            free(ref); goto base_cpu_cleanup_output;
        }

        float max_diff = max_abs_diff((float*)output->data, ref, n_elem);
        int mismatch = 0;
        for (int64_t i = 0; i < n_elem; i++) {
            if (fabsf(((float*)output->data)[i] - ref[i]) > 1e-3f) mismatch++;
        }
        fprintf(stderr, "CPU  max_diff=%.2e  mismatches>1e-3: %d/%lld\n",
               max_diff, mismatch, (long long)n_elem);

        fprintf(stderr, "\n");

        int non_zero = 0;
        for (int64_t i = 0; i < n_elem; i++)
            if (fabsf(((float*)output->data)[i]) > 1e-6f) non_zero++;
        fprintf(stderr, "CPU  non_zero outputs: %d/%lld\n", non_zero, (long long)n_elem);

        if (max_diff < 1e-3f) {
            fprintf(stderr, "BERT-base CPU: PASS (max_diff=%.2e)\n", max_diff);
        } else {
            fprintf(stderr, "BERT-base CPU: max_diff=%.2e > 1e-3 (CHECK)\n", max_diff);
        }

        free(ref);
    }

base_cpu_cleanup_output:
    tensor_destroy(output);
base_cpu_cleanup_input:
    tensor_destroy(input);
base_cpu_cleanup_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * Phase B: BERT-base CUDA inference test
 * -------------------------------------------------------------------------- */
static void test_bert_base_cuda(void) {
#ifdef USE_CUDA
    fprintf(stderr, "\n=== BERT-base CUDA Inference (Phase B) ===\n");

    inference_session_t* sess = inference_session_load("tests/bert_base_test.onnx");
    if (!sess) { fprintf(stderr, "FAIL: CUDA model load NULL\n"); return; }

    int64_t input_shape[] = {1, 8};
    tensor_t* input = tensor_create(DATA_TYPE_I64, 2, input_shape);
    if (!input) { fprintf(stderr, "FAIL: CUDA tensor_create input\n"); goto base_cu_cleanup_sess; }
    {
        float tmp[8];
        if (load_binary("tests/bert_base_input.bin", tmp, 8 * sizeof(float)) != 0) {
            fprintf(stderr, "FAIL: CUDA load input\n"); goto base_cu_cleanup_input;
        }
        int64_t* ids = (int64_t*)input->data;
        for (int i = 0; i < 8; i++) ids[i] = (int64_t)tmp[i];
    }

    int64_t output_shape[] = {1, 257};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, output_shape);
    if (!output) { fprintf(stderr, "FAIL: CUDA tensor_create output\n"); goto base_cu_cleanup_input; }

    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        fprintf(stderr, "CUDA: running inference...\n");
        int rc = inference_session_run(sess, inputs, outputs, 1);
        fprintf(stderr, "CUDA: inference result=%d\n", rc);
        if (rc != 0) {
            fprintf(stderr, "FAIL: CUDA inference_session_run\n"); goto base_cu_cleanup_output;
        }
    }

    {
        int64_t n_elem = 1 * 257;
        float* ref = (float*)malloc(n_elem * sizeof(float));
        if (!ref) goto base_cu_cleanup_output;
        if (load_binary("tests/bert_base_ref_output.bin", ref,
                        n_elem * sizeof(float)) != 0) {
            free(ref); goto base_cu_cleanup_output;
        }

        float max_diff = max_abs_diff((float*)output->data, ref, n_elem);
        fprintf(stderr, "CUDA max_diff=%.2e\n", max_diff);

        int mismatch = 0;
        for (int64_t i = 0; i < n_elem; i++) {
            if (fabsf(((float*)output->data)[i] - ref[i]) > 5e-3f) mismatch++;
        }
        fprintf(stderr, "CUDA mismatches>5e-3: %d/%lld\n", mismatch, (long long)n_elem);

        if (max_diff < 5e-3f) {
            fprintf(stderr, "BERT-base CUDA: PASS (max_diff=%.2e)\n", max_diff);
        } else {
            fprintf(stderr, "BERT-base CUDA: max_diff=%.2e > 5e-3 (CHECK)\n", max_diff);
        }

        free(ref);
    }

base_cu_cleanup_output:
    tensor_destroy(output);
base_cu_cleanup_input:
    tensor_destroy(input);
base_cu_cleanup_sess:
    inference_session_destroy(sess);
#else
    (void)0;
#endif
}

/* --------------------------------------------------------------------------
 * Main
 * -------------------------------------------------------------------------- */
int main(void) {
    platform_init();
    operator_init_all();
#ifdef USE_CUDA
    cuda_platform_init(0);
#endif

    /* Phase A: BERT-like test */
    test_bert_cpu();
    fprintf(stderr, "\n=== BERT CPU: DONE ===\n");

    /* Phase B: BERT-base test */
    test_bert_base_cpu();
    fprintf(stderr, "\n=== BERT-base CPU: DONE ===\n");

#ifdef USE_CUDA
    test_bert_cuda();
    fprintf(stderr, "\n=== BERT CUDA: DONE ===\n");

    test_bert_base_cuda();
    fprintf(stderr, "\n=== BERT-base CUDA: DONE ===\n");

    cuda_platform_finalize();
#endif
    platform_finalize();
    return 0;
}
