#include "unity.h"
#include "onnx_parser.h"
#include "onnx_loader.h"
#include "inference_engine.h"
#include "operator.h"
#include "platform.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* ============================================================
 * Embedded ONNX model bytes (generated by gen_onnx_test.py)
 * ============================================================ */

/* test_relu.onnx (72 bytes): Input(1x4) -> ReLU -> Output(1x4) */
static const unsigned char onnx_test_relu_data[] = {
    0x3A, 0x46, 0x0A, 0x15, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x12, 0x06, 0x6F, 0x75, 0x74,
    0x70, 0x75, 0x74, 0x22, 0x04, 0x52, 0x65, 0x6C, 0x75, 0x5A, 0x15, 0x0A, 0x05, 0x69, 0x6E, 0x70,
    0x75, 0x74, 0x2A, 0x0C, 0x0A, 0x0A, 0x12, 0x08, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x04,
    0x62, 0x16, 0x0A, 0x06, 0x6F, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2A, 0x0C, 0x0A, 0x0A, 0x12, 0x08,
    0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x04
};
static const size_t onnx_test_relu_data_len = 72;

/* test_chain.onnx (96 bytes): Input(1x4) -> ReLU -> ReLU -> Output(1x4) */
static const unsigned char onnx_test_chain_data[] = {
    0x3A, 0x5E, 0x0A, 0x15, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x12, 0x06, 0x68, 0x69, 0x64,
    0x64, 0x65, 0x6E, 0x22, 0x04, 0x52, 0x65, 0x6C, 0x75, 0x0A, 0x16, 0x0A, 0x06, 0x68, 0x69, 0x64,
    0x64, 0x65, 0x6E, 0x12, 0x06, 0x6F, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x04, 0x52, 0x65, 0x6C,
    0x75, 0x5A, 0x15, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x2A, 0x0C, 0x0A, 0x0A, 0x12, 0x08,
    0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x04, 0x62, 0x16, 0x0A, 0x06, 0x6F, 0x75, 0x74, 0x70,
    0x75, 0x74, 0x2A, 0x0C, 0x0A, 0x0A, 0x12, 0x08, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x04
};
static const size_t onnx_test_chain_data_len = 96;

/* test_conv.onnx (220 bytes): Input(1x1x3x3) -> Conv(identity 2x2) -> ReLU -> Output(1x1x2x2) */
static const unsigned char onnx_test_conv_data[] = {
    0x3A, 0xD9, 0x01, 0x0A, 0x55, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x0A, 0x0B, 0x63, 0x6F,
    0x6E, 0x76, 0x2E, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x08, 0x63, 0x6F, 0x6E, 0x76, 0x5F,
    0x6F, 0x75, 0x74, 0x22, 0x04, 0x43, 0x6F, 0x6E, 0x76, 0x2A, 0x12, 0x0A, 0x0C, 0x6B, 0x65, 0x72,
    0x6E, 0x65, 0x6C, 0x5F, 0x73, 0x68, 0x61, 0x70, 0x65, 0x42, 0x02, 0x02, 0x02, 0x2A, 0x0D, 0x0A,
    0x07, 0x73, 0x74, 0x72, 0x69, 0x64, 0x65, 0x73, 0x42, 0x02, 0x01, 0x01, 0x2A, 0x0C, 0x0A, 0x04,
    0x70, 0x61, 0x64, 0x73, 0x42, 0x04, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x18, 0x0A, 0x08, 0x63, 0x6F,
    0x6E, 0x76, 0x5F, 0x6F, 0x75, 0x74, 0x12, 0x06, 0x6F, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x04,
    0x52, 0x65, 0x6C, 0x75, 0x2A, 0x27, 0x42, 0x0B, 0x63, 0x6F, 0x6E, 0x76, 0x2E, 0x77, 0x65, 0x69,
    0x67, 0x68, 0x74, 0x0A, 0x04, 0x01, 0x01, 0x02, 0x02, 0x10, 0x01, 0x4A, 0x10, 0x00, 0x00, 0x80,
    0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x5A, 0x1D, 0x0A,
    0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x2A, 0x14, 0x0A, 0x12, 0x12, 0x10, 0x0A, 0x02, 0x08, 0x01,
    0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x03, 0x0A, 0x02, 0x08, 0x03, 0x62, 0x1E, 0x0A, 0x06,
    0x6F, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2A, 0x14, 0x0A, 0x12, 0x12, 0x10, 0x0A, 0x02, 0x08, 0x01,
    0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x02, 0x0A, 0x02, 0x08, 0x02
};
static const size_t onnx_test_conv_data_len = 220;

/* test_pipeline.onnx (286 bytes): Input(1,1,4,4) -> Conv(K=2,k=2) -> ReLU -> Output(1,2,3,3)
   Generated by onnx.helper (standard ONNX library), validates real-model compatibility. */
static const unsigned char onnx_test_pipeline_data[] = {
    0x08, 0x0D, 0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5F, 0x67, 0x65, 0x6E, 0x3A, 0x8B, 0x02, 0x0A,
    0x61, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74, 0x0A, 0x0C, 0x63, 0x6F, 0x6E, 0x76, 0x31, 0x2E,
    0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x08, 0x63, 0x6F, 0x6E, 0x76, 0x5F, 0x6F, 0x75, 0x74,
    0x22, 0x04, 0x43, 0x6F, 0x6E, 0x76, 0x2A, 0x15, 0x0A, 0x0C, 0x6B, 0x65, 0x72, 0x6E, 0x65, 0x6C,
    0x5F, 0x73, 0x68, 0x61, 0x70, 0x65, 0x40, 0x02, 0x40, 0x02, 0xA0, 0x01, 0x07, 0x2A, 0x11, 0x0A,
    0x04, 0x70, 0x61, 0x64, 0x73, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0x40, 0x00, 0xA0, 0x01, 0x07,
    0x2A, 0x10, 0x0A, 0x07, 0x73, 0x74, 0x72, 0x69, 0x64, 0x65, 0x73, 0x40, 0x01, 0x40, 0x01, 0xA0,
    0x01, 0x07, 0x0A, 0x18, 0x0A, 0x08, 0x63, 0x6F, 0x6E, 0x76, 0x5F, 0x6F, 0x75, 0x74, 0x12, 0x06,
    0x6F, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x04, 0x52, 0x65, 0x6C, 0x75, 0x12, 0x0D, 0x74, 0x65,
    0x73, 0x74, 0x5F, 0x70, 0x69, 0x70, 0x65, 0x6C, 0x69, 0x6E, 0x65, 0x2A, 0x3A, 0x08, 0x02, 0x08,
    0x01, 0x08, 0x02, 0x08, 0x02, 0x10, 0x01, 0x22, 0x20, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00,
    0x40, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0,
    0x40, 0x00, 0x00, 0xE0, 0x40, 0x00, 0x00, 0x00, 0x41, 0x42, 0x0C, 0x63, 0x6F, 0x6E, 0x76, 0x31,
    0x2E, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5A, 0x1F, 0x0A, 0x05, 0x69, 0x6E, 0x70, 0x75, 0x74,
    0x12, 0x16, 0x0A, 0x14, 0x08, 0x01, 0x12, 0x10, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x01,
    0x0A, 0x02, 0x08, 0x04, 0x0A, 0x02, 0x08, 0x04, 0x62, 0x20, 0x0A, 0x06, 0x6F, 0x75, 0x74, 0x70,
    0x75, 0x74, 0x12, 0x16, 0x0A, 0x14, 0x08, 0x01, 0x12, 0x10, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02,
    0x08, 0x02, 0x0A, 0x02, 0x08, 0x03, 0x0A, 0x02, 0x08, 0x03, 0x42, 0x02, 0x10, 0x0B
};
static const size_t onnx_test_pipeline_data_len = 286;

/* ============================================================
 * Helper: write embedded bytes to temp file
 * ============================================================ */
static int write_temp_onnx(const char* name, const unsigned char* data, size_t len,
                           char* out_path, size_t path_sz) {
    snprintf(out_path, path_sz, "%s", name);
    FILE* fp = fopen(out_path, "wb");
    if (!fp) return -1;
    size_t w = fwrite(data, 1, len, fp);
    fclose(fp);
    return (w == len) ? 0 : -1;
}

static void remove_temp_file(const char* path) {
    remove(path);
}

/* ============================================================
 * Protobuf parser unit tests
 * ============================================================ */

void test_varint_decode_single_byte(void) {
    const uint8_t data[] = {0x01};  /* value = 1 */
    pb_message_t* msg = pb_parse_message(data, 1, 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(0, msg->count);  /* field 0 → no fields, varint has fn=0 */
    pb_message_destroy(msg);
}

void test_varint_decode_two_bytes(void) {
    /* field 1, wire type 0, value 150 (tag=0x08, value=0x96 0x01) */
    const uint8_t data[] = {0x08, 0x96, 0x01};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(1, msg->count);
    TEST_ASSERT_EQUAL(1, msg->fields[0].field_number);
    TEST_ASSERT_EQUAL(150, (int)msg->fields[0].varint_value);
    pb_message_destroy(msg);
}

void test_varint_decode_max(void) {
    /* field 1, wire type 0, value 0xFFFFFFFFFFFFFFFF (10 bytes of 0xFF then 0x01) */
    const uint8_t data[] = {0x08, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
                             0xFF, 0xFF, 0xFF, 0xFF, 0x01};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(1, msg->count);
    TEST_ASSERT_EQUAL(1, msg->fields[0].field_number);
    pb_message_destroy(msg);
}

void test_length_delimited_string(void) {
    /* field 1 (tag=0x0A), len=5, "hello" */
    const uint8_t data[] = {0x0A, 0x05, 'h', 'e', 'l', 'l', 'o'};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(1, msg->count);
    TEST_ASSERT_EQUAL(1, msg->fields[0].field_number);
    TEST_ASSERT_EQUAL(PB_WIRE_LENGTH_DELIMITED, msg->fields[0].wire_type);
    TEST_ASSERT_EQUAL(5, (int)msg->fields[0].length_delimited.size);
    TEST_ASSERT_EQUAL('h', msg->fields[0].length_delimited.data[0]);
    TEST_ASSERT_EQUAL('o', msg->fields[0].length_delimited.data[4]);
    pb_message_destroy(msg);
}

void test_nested_message(void) {
    /* Outer message:
       field 1 (length-delimited) containing:
         field 2 (varint, value=42)
       = 0x0A 0x02  0x10 0x2A
    */
    const uint8_t data[] = {0x0A, 0x02, 0x10, 0x2A};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(1, msg->count);
    TEST_ASSERT_EQUAL(1, msg->fields[0].field_number);

    pb_message_t* inner = pb_field_as_message(&msg->fields[0], 4);
    TEST_ASSERT_NOT_NULL(inner);
    TEST_ASSERT_EQUAL(1, inner->count);
    TEST_ASSERT_EQUAL(2, inner->fields[0].field_number);
    TEST_ASSERT_EQUAL(42, (int)inner->fields[0].varint_value);
    pb_message_destroy(inner);
    pb_message_destroy(msg);
}

void test_multiple_fields(void) {
    /* field 1 varint=10, field 2 varint=20, field 3 varint=30 */
    const uint8_t data[] = {0x08, 0x0A, 0x10, 0x14, 0x18, 0x1E};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(3, msg->count);
    TEST_ASSERT_EQUAL(1, msg->fields[0].field_number);
    TEST_ASSERT_EQUAL(10, (int)msg->fields[0].varint_value);
    TEST_ASSERT_EQUAL(2, msg->fields[1].field_number);
    TEST_ASSERT_EQUAL(20, (int)msg->fields[1].varint_value);
    TEST_ASSERT_EQUAL(3, msg->fields[2].field_number);
    TEST_ASSERT_EQUAL(30, (int)msg->fields[2].varint_value);
    pb_message_destroy(msg);
}

void test_pb_find_field(void) {
    const uint8_t data[] = {0x08, 0x0A, 0x10, 0x14, 0x18, 0x1E};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    pb_field_t* f = pb_find_field(msg, 2);
    TEST_ASSERT_NOT_NULL(f);
    TEST_ASSERT_EQUAL(20, (int)f->varint_value);
    f = pb_find_field(msg, 99);
    TEST_ASSERT_NULL(f);
    pb_message_destroy(msg);
}

void test_pb_find_all_fields(void) {
    /* field 1 varint=10, field 2 varint=20, field 1 varint=30 */
    const uint8_t data[] = {0x08, 0x0A, 0x10, 0x14, 0x08, 0x1E};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    pb_field_t** arr = NULL;
    int cnt = 0;
    int rc = pb_find_all_fields(msg, 1, &arr, &cnt);
    TEST_ASSERT_EQUAL(0, rc);
    TEST_ASSERT_EQUAL(2, cnt);
    TEST_ASSERT_EQUAL(10, (int)arr[0]->varint_value);
    TEST_ASSERT_EQUAL(30, (int)arr[1]->varint_value);
    free(arr);
    pb_message_destroy(msg);
}

void test_pb_field_get_int64(void) {
    const uint8_t data[] = {0x08, 0x96, 0x01, 0x10, 0x14};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    TEST_ASSERT_EQUAL(150, (int)pb_field_get_int64(msg, 1, 0));
    TEST_ASSERT_EQUAL(20, (int)pb_field_get_int64(msg, 2, 0));
    TEST_ASSERT_EQUAL(99, (int)pb_field_get_int64(msg, 99, 99));  /* default */
    pb_message_destroy(msg);
}

void test_pb_field_get_string(void) {
    const uint8_t data[] = {0x0A, 0x04, 't', 'e', 's', 't'};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    size_t slen = 0;
    const uint8_t* s = pb_field_get_string(msg, 1, &slen);
    TEST_ASSERT_NOT_NULL(s);
    TEST_ASSERT_EQUAL(4, (int)slen);
    TEST_ASSERT_EQUAL('t', s[0]);
    TEST_ASSERT_EQUAL('t', s[3]);
    pb_message_destroy(msg);
}

void test_decode_packed_varints(void) {
    /* Packed: [1, 2, 3, 4] as LEB128 bytes */
    const uint8_t data[] = {0x01, 0x02, 0x03, 0x04};
    int64_t vals[8];
    int cnt = 0;
    int rc = pb_decode_packed_varints(data, sizeof(data), vals, 8, &cnt);
    TEST_ASSERT_EQUAL(0, rc);
    TEST_ASSERT_EQUAL(4, cnt);
    TEST_ASSERT_EQUAL(1, (int)vals[0]);
    TEST_ASSERT_EQUAL(4, (int)vals[3]);
}

void test_decode_float_data(void) {
    /* 1.0f, 2.0f as little-endian bytes */
    float f1 = 1.0f, f2 = 2.0f;
    uint8_t data[8];
    memcpy(data, &f1, 4);
    memcpy(data + 4, &f2, 4);
    float vals[4];
    int cnt = 0;
    int rc = pb_decode_float_data(data, sizeof(data), vals, 4, &cnt);
    TEST_ASSERT_EQUAL(0, rc);
    TEST_ASSERT_EQUAL(2, cnt);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 1.0f, vals[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 2.0f, vals[1]);
}

void test_empty_message(void) {
    pb_message_t* msg = pb_parse_message(NULL, 0, 5);
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(0, msg->count);
    pb_message_destroy(msg);
}

void test_truncated_varint(void) {
    /* Truncated: tag byte 0x08 starts varint field 1, but nothing follows */
    const uint8_t data[] = {0x08};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 5);
    /* Should fail on truncated varint value */
    TEST_ASSERT_NOT_NULL(msg);
    TEST_ASSERT_EQUAL(0, msg->count);
    pb_message_destroy(msg);
}

void test_max_depth_exceeded(void) {
    /* Nested: field 1 containing field 1 containing ... */
    const uint8_t data[] = {0x0A, 0x02, 0x0A, 0x00};
    pb_message_t* msg = pb_parse_message(data, sizeof(data), 1);
    TEST_ASSERT_NOT_NULL(msg);
    /* Inner nested parse called from pb_parse_message with max_depth=1
       won't parse deeper than depth 1 */
    pb_message_destroy(msg);

    pb_message_t* msg2 = pb_parse_message(data, sizeof(data), 0);
    TEST_ASSERT_NULL(msg2);
}

void test_pb_field_as_message_null(void) {
    pb_message_t* m = pb_field_as_message(NULL, 1);
    TEST_ASSERT_NULL(m);
}

void test_pb_find_all_fields_empty(void) {
    pb_field_t** arr = NULL;
    int cnt = 0;
    int rc = pb_find_all_fields(NULL, 1, &arr, &cnt);
    TEST_ASSERT_EQUAL(-1, rc);
    TEST_ASSERT_EQUAL(0, cnt);
    TEST_ASSERT_NULL(arr);
}

void test_pb_message_destroy_null(void) {
    pb_message_destroy(NULL);  /* should not crash */
}

/* ============================================================
 * ONNX loader unit tests
 * ============================================================ */

void test_onnx_load_null_path(void) {
    onnx_model_t* m = onnx_load_from_file(NULL);
    TEST_ASSERT_NULL(m);
}

void test_onnx_load_nonexistent_file(void) {
    onnx_model_t* m = onnx_load_from_file("__nonexistent_file__.onnx");
    TEST_ASSERT_NULL(m);
}

void test_onnx_model_destroy_null(void) {
    onnx_model_destroy(NULL);  /* should not crash */
}

/* ============================================================
 * Integration test: ReLU model (CPU)
 * ============================================================ */
void test_relu_model_cpu(void) {
    char path[512];
    int rc = write_temp_onnx("test_relu_cpu.onnx",
                              onnx_test_relu_data, onnx_test_relu_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    TEST_ASSERT_EQUAL(1, inference_session_num_inputs(session));
    TEST_ASSERT_EQUAL(1, inference_session_num_outputs(session));

    /* Create input: [-1, 0, 2, -3] */
    int64_t shape[] = {1, 4};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 2, shape);
    float* idata = (float*)input->data;
    idata[0] = -1.0f; idata[1] = 0.0f; idata[2] = 2.0f; idata[3] = -3.0f;

    tensor_t* input_arr[] = {input};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 0);  /* CPU */
    TEST_ASSERT_EQUAL(0, rc);

    float* odata = (float*)output->data;
    /* ReLU: [-1,0,2,-3] -> [0,0,2,0] */
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[1]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 2.0f, odata[2]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[3]);

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

/* ============================================================
 * Integration test: Chain model (ReLU → ReLU) CPU
 * ============================================================ */
void test_chain_model_cpu(void) {
    char path[512];
    int rc = write_temp_onnx("test_chain_cpu.onnx",
                              onnx_test_chain_data, onnx_test_chain_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    int64_t shape[] = {1, 4};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 2, shape);
    float* idata = (float*)input->data;
    idata[0] = -1.0f; idata[1] = 0.0f; idata[2] = 2.0f; idata[3] = -3.0f;

    tensor_t* input_arr[] = {input};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 0);
    TEST_ASSERT_EQUAL(0, rc);

    float* odata = (float*)output->data;
    /* ReLU(ReLU(x)) == ReLU(x): [-1,0,2,-3] -> [0,0,2,0] */
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[1]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 2.0f, odata[2]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[3]);

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

/* ============================================================
 * Integration test: Conv2D + ReLU model (CPU)
 * ============================================================ */
void test_conv_model_cpu(void) {
    char path[512];
    int rc = write_temp_onnx("test_conv_cpu.onnx",
                              onnx_test_conv_data, onnx_test_conv_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    /* Input 1x1x3x3 = [1,2,3, 4,5,6, 7,8,9]
       Identity kernel [[1,0],[0,1]], 2x2, stride=1, pad=0
       Output = [1*1+0*2+0*4+1*5,  1*2+0*3+0*5+1*6,
                 1*4+0*5+0*7+1*8,  1*5+0*6+0*8+1*9]
              = [1+5, 2+6, 4+8, 5+9] = [6, 8, 12, 14]
       Then ReLU (all positive) → same */
    int64_t shape[] = {1, 1, 3, 3};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, shape);
    float* idata = (float*)input->data;
    idata[0] = 1.0f; idata[1] = 2.0f; idata[2] = 3.0f;
    idata[3] = 4.0f; idata[4] = 5.0f; idata[5] = 6.0f;
    idata[6] = 7.0f; idata[7] = 8.0f; idata[8] = 9.0f;

    tensor_t* input_arr[] = {input};

    int64_t out_shape[] = {1, 1, 2, 2};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 4, out_shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 0);
    TEST_ASSERT_EQUAL(0, rc);

    float* odata = (float*)output->data;
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 6.0f,  odata[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 8.0f,  odata[1]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 12.0f, odata[2]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 14.0f, odata[3]);

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

/* ============================================================
 * Integration test: ReLU model (CUDA)
 * ============================================================ */
/* ============================================================
 * Integration test: Pipeline model (Conv+ReLU from real ONNX library)
 * ============================================================ */
void test_pipeline_model_cpu(void) {
    char path[512];
    int rc = write_temp_onnx("test_pipeline_cpu.onnx",
                              onnx_test_pipeline_data, onnx_test_pipeline_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    /* Input 1x1x4x4 = [1..16] */
    int64_t shape[] = {1, 1, 4, 4};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, shape);
    float* idata = (float*)input->data;
    for (int i = 0; i < 16; i++) idata[i] = (float)(i + 1);

    tensor_t* input_arr[] = {input};

    int64_t out_shape[] = {1, 2, 3, 3};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 4, out_shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 0);
    TEST_ASSERT_EQUAL(0, rc);

    float* odata = (float*)output->data;
    /* Expected: Conv(K=2, identity-ish weights) then ReLU */
    float expected[] = {
        44.f, 54.f, 64.f,
        84.f, 94.f, 104.f,
        124.f, 134.f, 144.f,
        100.f, 126.f, 152.f,
        204.f, 230.f, 256.f,
        308.f, 334.f, 360.f
    };
    for (int i = 0; i < 18; i++) {
        TEST_ASSERT_FLOAT_WITHIN(0.1f, expected[i], odata[i]);
    }

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

#ifdef USE_CUDA
void test_relu_model_cuda(void) {
    char path[512];
    int rc = write_temp_onnx("test_relu_cuda.onnx",
                              onnx_test_relu_data, onnx_test_relu_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    int64_t shape[] = {1, 4};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 2, shape);
    float* idata = (float*)input->data;
    idata[0] = -1.0f; idata[1] = 0.0f; idata[2] = 2.0f; idata[3] = -3.0f;
    tensor_copy_to_device(input);

    tensor_t* input_arr[] = {input};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 2, shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 1);  /* CUDA */
    TEST_ASSERT_EQUAL(0, rc);

    tensor_copy_to_host(output);
    float* odata = (float*)output->data;
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[1]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 2.0f, odata[2]);
    TEST_ASSERT_FLOAT_WITHIN(0.001f, 0.0f, odata[3]);

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

void test_conv_model_cuda(void) {
    char path[512];
    int rc = write_temp_onnx("test_conv_cuda.onnx",
                              onnx_test_conv_data, onnx_test_conv_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    int64_t shape[] = {1, 1, 3, 3};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, shape);
    float* idata = (float*)input->data;
    idata[0] = 1.0f; idata[1] = 2.0f; idata[2] = 3.0f;
    idata[3] = 4.0f; idata[4] = 5.0f; idata[5] = 6.0f;
    idata[6] = 7.0f; idata[7] = 8.0f; idata[8] = 9.0f;
    tensor_copy_to_device(input);

    tensor_t* input_arr[] = {input};

    int64_t out_shape[] = {1, 1, 2, 2};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 4, out_shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 1);  /* CUDA */
    TEST_ASSERT_EQUAL(0, rc);

    tensor_copy_to_host(output);
    float* odata = (float*)output->data;
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 6.0f,  odata[0]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 8.0f,  odata[1]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 12.0f, odata[2]);
    TEST_ASSERT_FLOAT_WITHIN(0.01f, 14.0f, odata[3]);

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}

void test_pipeline_model_cuda(void) {
    char path[512];
    int rc = write_temp_onnx("test_pipeline_cuda.onnx",
                              onnx_test_pipeline_data, onnx_test_pipeline_data_len,
                              path, sizeof(path));
    TEST_ASSERT_EQUAL(0, rc);

    inference_session_t* session = inference_session_load(path);
    TEST_ASSERT_NOT_NULL(session);
    remove_temp_file(path);

    int64_t shape[] = {1, 1, 4, 4};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, shape);
    float* idata = (float*)input->data;
    for (int i = 0; i < 16; i++) idata[i] = (float)(i + 1);
    tensor_copy_to_device(input);

    tensor_t* input_arr[] = {input};

    int64_t out_shape[] = {1, 2, 3, 3};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 4, out_shape);
    tensor_t* output_arr[] = {output};

    rc = inference_session_run(session, input_arr, output_arr, 1);  /* CUDA */
    TEST_ASSERT_EQUAL(0, rc);

    tensor_copy_to_host(output);
    float* odata = (float*)output->data;
    float expected[] = {
        44.f, 54.f, 64.f,
        84.f, 94.f, 104.f,
        124.f, 134.f, 144.f,
        100.f, 126.f, 152.f,
        204.f, 230.f, 256.f,
        308.f, 334.f, 360.f
    };
    for (int i = 0; i < 18; i++) {
        TEST_ASSERT_FLOAT_WITHIN(0.1f, expected[i], odata[i]);
    }

    tensor_destroy(input);
    tensor_destroy(output);
    inference_session_destroy(session);
}
#endif /* USE_CUDA */

extern int operator_init_all(void);
#ifdef USE_CUDA
extern int cuda_platform_init(int device_id);
#endif

/* ============================================================
 * Unity boilerplate
 * ============================================================ */
void setUp(void) {}
void tearDown(void) {}

/* ============================================================
 * Main
 * ============================================================ */
int main(void) {
    platform_init();
    operator_init_all();
#ifdef USE_CUDA
    cuda_platform_init(0);
#endif
    UNITY_BEGIN();

    /* Protobuf parser unit tests */
    RUN_TEST(test_varint_decode_single_byte);
    RUN_TEST(test_varint_decode_two_bytes);
    RUN_TEST(test_varint_decode_max);
    RUN_TEST(test_length_delimited_string);
    RUN_TEST(test_nested_message);
    RUN_TEST(test_multiple_fields);
    RUN_TEST(test_pb_find_field);
    RUN_TEST(test_pb_find_all_fields);
    RUN_TEST(test_pb_field_get_int64);
    RUN_TEST(test_pb_field_get_string);
    RUN_TEST(test_decode_packed_varints);
    RUN_TEST(test_decode_float_data);
    RUN_TEST(test_empty_message);
    RUN_TEST(test_truncated_varint);
    RUN_TEST(test_max_depth_exceeded);
    RUN_TEST(test_pb_field_as_message_null);
    RUN_TEST(test_pb_find_all_fields_empty);
    RUN_TEST(test_pb_message_destroy_null);

    /* ONNX loader unit tests */
    RUN_TEST(test_onnx_load_null_path);
    RUN_TEST(test_onnx_load_nonexistent_file);
    RUN_TEST(test_onnx_model_destroy_null);

    /* Integration tests (CPU) */
    RUN_TEST(test_relu_model_cpu);
    RUN_TEST(test_chain_model_cpu);
    RUN_TEST(test_conv_model_cpu);
    RUN_TEST(test_pipeline_model_cpu);

    /* Integration tests (CUDA) */
#ifdef USE_CUDA
    RUN_TEST(test_relu_model_cuda);
    RUN_TEST(test_conv_model_cuda);
    RUN_TEST(test_pipeline_model_cuda);
#endif

    return UNITY_END();
}
