/**
 * YOLOv8n end-to-end inference test (CPU + CUDA).
 *
 * Requires model and test data generated by gen_yolo_test.py.
 * Input:  1x3x640x640 F32 tensor
 * Output: 1x84x8400 F32 tensor (80 classes + 4 bbox coords)
 * Reference: PyTorch output
 */

#include "unity.h"
#include "inference_engine.h"
#include "platform.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifdef USE_CUDA
#include "cuda_platform.h"
#endif

extern int operator_init_all(void);

void setUp(void) {}
void tearDown(void) {}

static int load_binary(const char* path, void* buf, size_t expected_bytes) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "Cannot open %s\n", path); return -1; }
    size_t n = fread(buf, 1, expected_bytes, f);
    fclose(f);
    if (n != expected_bytes) {
        fprintf(stderr, "Short read from %s: %zu/%zu\n", path, n, expected_bytes);
        return -1;
    }
    return 0;
}

static float compute_max_diff(const float* a, const float* b, int64_t n) {
    float max_diff = 0.0f;
    for (int64_t i = 0; i < n; i++) {
        float diff = fabsf(a[i] - b[i]);
        if (diff > max_diff) max_diff = diff;
    }
    return max_diff;
}

static int count_mismatches(const float* a, const float* b, int64_t n, float threshold) {
    int count = 0;
    for (int64_t i = 0; i < n; i++) {
        if (fabsf(a[i] - b[i]) > threshold) count++;
    }
    return count;
}

/* --------------------------------------------------------------------------
 * CPU inference test
 * -------------------------------------------------------------------------- */
void test_yolov8n_cpu(void) {
    inference_session_t* sess = inference_session_load("tests/yolov8n_test.onnx");
    if (!sess) { fprintf(stderr, "SKIP: model not found (run gen_yolo_test.py first)\n"); return; }

    /* Input: 1x3x640x640 */
    int64_t input_shape[] = {1, 3, 640, 640};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, input_shape);
    if (!input) { fprintf(stderr, "FAIL: tensor_create input\n"); goto cpu_sess; }
    size_t input_bytes = (size_t)(1 * 3 * 640 * 640 * (int64_t)sizeof(float));
    if (load_binary("tests/yolov8n_input.bin", input->data, input_bytes) != 0) {
        fprintf(stderr, "SKIP: input data not found\n"); goto cpu_input;
    }

    /* Output: 1x84x8400 */
    int64_t output_shape[] = {1, 84, 8400};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 3, output_shape);
    if (!output) { fprintf(stderr, "FAIL: tensor_create output\n"); goto cpu_input; }

    /* Run */
    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        int rc = inference_session_run(sess, inputs, outputs, 0);
        if (rc != 0) { fprintf(stderr, "FAIL: CPU inference error %d\n", rc); goto cpu_output; }
    }

    /* Compare */
    {
        int64_t numel = 1 * 84 * 8400;
        size_t ref_bytes = (size_t)numel * sizeof(float);
        float* ref = (float*)malloc(ref_bytes);
        if (!ref) goto cpu_output;
        if (load_binary("tests/yolov8n_ref_output.bin", ref, ref_bytes) != 0) {
            fprintf(stderr, "SKIP: reference data not found\n"); free(ref); goto cpu_output;
        }

        float max_diff = compute_max_diff((float*)output->data, ref, numel);
        int mismatches = count_mismatches((float*)output->data, ref, numel, 1e-2f);

        fprintf(stderr, "CPU vs PyTorch: max_diff=%.2e  mismatches>1e-2=%d/%lld\n",
               max_diff, mismatches, (long long)numel);
        free(ref);
    }

cpu_output:
    tensor_destroy(output);
cpu_input:
    tensor_destroy(input);
cpu_sess:
    inference_session_destroy(sess);
}

/* --------------------------------------------------------------------------
 * CUDA inference test
 * -------------------------------------------------------------------------- */
void test_yolov8n_cuda(void) {

    inference_session_t* sess = inference_session_load("tests/yolov8n_test.onnx");
    if (!sess) { fprintf(stderr, "SKIP: model not found\n"); return; }

    int64_t input_shape[] = {1, 3, 640, 640};
    tensor_t* input = tensor_create(DATA_TYPE_F32, 4, input_shape);
    if (!input) { fprintf(stderr, "FAIL: CUDA tensor_create input\n"); goto cuda_sess; }
    size_t input_bytes = (size_t)(1 * 3 * 640 * 640 * (int64_t)sizeof(float));
    if (load_binary("tests/yolov8n_input.bin", input->data, input_bytes) != 0) {
        fprintf(stderr, "SKIP: input data not found\n"); goto cuda_input;
    }

    int64_t output_shape[] = {1, 84, 8400};
    tensor_t* output = tensor_create(DATA_TYPE_F32, 3, output_shape);
    if (!output) { fprintf(stderr, "FAIL: CUDA tensor_create output\n"); goto cuda_input; }

    {
        tensor_t* inputs[]  = {input};
        tensor_t* outputs[] = {output};
        int rc = inference_session_run(sess, inputs, outputs, 1);
        if (rc != 0) { fprintf(stderr, "FAIL: CUDA inference error\n"); goto cuda_output; }
    }

    {
        int64_t numel = 1 * 84 * 8400;
        size_t ref_bytes = (size_t)numel * sizeof(float);
        float* ref = (float*)malloc(ref_bytes);
        if (!ref) goto cuda_output;
        if (load_binary("tests/yolov8n_ref_output.bin", ref, ref_bytes) != 0) {
            fprintf(stderr, "SKIP: reference data not found\n"); free(ref); goto cuda_output;
        }

        float max_diff = compute_max_diff((float*)output->data, ref, numel);
        int mismatches = count_mismatches((float*)output->data, ref, numel, 1e-2f);

        fprintf(stderr, "CUDA vs PyTorch: max_diff=%.2e  mismatches>1e-2=%d/%lld\n",
               max_diff, mismatches, (long long)numel);
        free(ref);
    }

cuda_output:
    tensor_destroy(output);
cuda_input:
    tensor_destroy(input);
cuda_sess:
    inference_session_destroy(sess);
}

int main(void) {
    platform_init();
    operator_init_all();
#ifdef USE_CUDA
    cuda_platform_init(0);
#endif

    test_yolov8n_cpu();

#ifdef USE_CUDA
    test_yolov8n_cuda();
    cuda_platform_finalize();
#endif
    platform_finalize();
    return 0;
}
