#include "operator.h"

int register_relu_f32(void);
int register_matmul_f32(void);
int register_conv2d_f32(void);
int register_activations(void);
int register_pooling(void);
int register_batchnorm(void);
int register_add_f32(void);
int register_reshape_f32(void);
int register_globalavgpool_f32(void);
int register_softmax_f32(void);
int register_mul_f32(void);
int register_concat_f32(void);
int register_resize_f32(void);
int register_transpose_f32(void);
int register_sub_f32(void);
int register_div_f32(void);
int register_slice_f32(void);
int register_split_f32(void);
int register_layernorm_f32(void);
int register_gather_f32(void);
int register_squeeze_unsqueeze_f32(void);
int register_reduce_f32(void);
int register_cast_f32(void);
int register_argmax_f32(void);
int register_mha_fused_f32(void);

/* CUDA operator registration (extern "C" from .cu files) */
int register_relu_f32_cuda(void);
int register_matmul_f32_cuda(void);
int register_conv2d_f32_cuda(void);
int register_activations_cuda(void);
int register_pooling_cuda(void);
int register_batchnorm_f32_cuda(void);
int register_add_f32_cuda(void);
int register_globalavgpool_f32_cuda(void);
int register_softmax_f32_cuda(void);
int register_reshape_f32_cuda(void);
int register_mul_f32_cuda(void);
int register_concat_f32_cuda(void);
int register_resize_f32_cuda(void);
int register_transpose_f32_cuda(void);
int register_sub_f32_cuda(void);
int register_div_f32_cuda(void);
int register_slice_f32_cuda(void);
int register_split_f32_cuda(void);
int register_layernorm_f32_cuda(void);
int register_gather_f32_cuda(void);
int register_squeeze_unsqueeze_f32_cuda(void);
int register_reduce_f32_cuda(void);
int register_cast_f32_cuda(void);
int register_argmax_f32_cuda(void);
int register_mha_fused_f32_cuda(void);

int operator_init_all(void) {
    int ret = 0;
    ret += register_relu_f32();
    ret += register_matmul_f32();
    ret += register_conv2d_f32();
    ret += register_activations();
    ret += register_pooling();
    ret += register_batchnorm();
    ret += register_add_f32();
    ret += register_reshape_f32();
    ret += register_globalavgpool_f32();
    ret += register_softmax_f32();
    ret += register_mul_f32();
    ret += register_concat_f32();
    ret += register_resize_f32();
    ret += register_transpose_f32();
    ret += register_sub_f32();
    ret += register_div_f32();
    ret += register_slice_f32();
    ret += register_split_f32();
    ret += register_layernorm_f32();
    ret += register_gather_f32();
    ret += register_squeeze_unsqueeze_f32();
    ret += register_reduce_f32();
    ret += register_cast_f32();
    ret += register_argmax_f32();
    ret += register_mha_fused_f32();
    ret += register_relu_f32_cuda();
    ret += register_matmul_f32_cuda();
    ret += register_conv2d_f32_cuda();
    ret += register_activations_cuda();
    ret += register_pooling_cuda();
    ret += register_batchnorm_f32_cuda();
    ret += register_add_f32_cuda();
    ret += register_globalavgpool_f32_cuda();
    ret += register_softmax_f32_cuda();
    ret += register_reshape_f32_cuda();
    ret += register_mul_f32_cuda();
    ret += register_concat_f32_cuda();
    ret += register_resize_f32_cuda();
    ret += register_transpose_f32_cuda();
    ret += register_sub_f32_cuda();
    ret += register_div_f32_cuda();
    ret += register_slice_f32_cuda();
    ret += register_split_f32_cuda();
    ret += register_layernorm_f32_cuda();
    ret += register_gather_f32_cuda();
    ret += register_squeeze_unsqueeze_f32_cuda();
    ret += register_reduce_f32_cuda();
    ret += register_cast_f32_cuda();
    ret += register_argmax_f32_cuda();
    ret += register_mha_fused_f32_cuda();
    return ret;
}
